dfneuf = read.csv(file = "dpe-v2-logements-neufs.csv")
dfex = read.csv(file = "dpe-v2-logements-existants.csv")
dim(dfneuf)
dim(dfex)
dfex = cbind(dfex,logement =c("existant"))
dfneuf = cbind(dfneuf,logement =c("neuf"))
dfneuf = cbind(dfneuf,Période_construction =c("après 2021"))
colcom = intersect(colnames(dfneuf),colnames(dfex))
df = rbind(dfex [ , colcom],dfneuf[ ,colcom])
df = cbind(df , année_DPE = format(as.Date(df$Date_réception_DPE), format = "%Y"))
summary(df)
df = cbind(df , verife_cout = df$Coût_total_5_usages == df$Coût_chauffage + df$Coût_éclairage + df$Coût_ECS + df$Coût_refroidissement + df$Coût_auxiliaires)
df = cbind(df , Cout_en_chaufage_p100 = df$Coût_chauffage/df$Coût_total_5_usages * 100)
x = table(df$Etiquette_DPE)
table(df$année_DPE)
table(df$logement)
table(df$Type_bâtiment)
table(df$Type_installation_chauffage)/nrow(df) * 100
table(df$Période_construction)
mean(df$Surface_habitable_logement, na.rm = TRUE)
mean(df$Coût_chauffage, na.rm = TRUE)
quantile(df$Coût_ECS)
quantile(df$Coût_ECS ,probs = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9))
cor(x = df$Surface_habitable_logement , y = df$Coût_chauffage, use = "complete.obs" )
v = c(df$Coût_total_5_usages,df$Coût_chauffage,df$Coût_éclairage,df$Coût_ECS,df$Coût_refroidissement,df$Coût_auxiliaires,df$Surface_habitable_logement,df$Emission_GES_5_usages)
plot(v)